### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by bkmar1192** [QNimbus/node-red-contrib-openhab-v2#10]
I am periodically getting the following error (I think it started after upgrading to OpenHAB 2.4 but can't 100% confirm).  The node will register events fine but every now and then I get the following error in the log and it delays the update.

type: Error: connection ended
    at IncomingMessage.<anonymous> (/Users/familymartin/.node-red/node_modules/@joeybaker/eventsource/lib/eventsource.js:133:28)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) }

**Comment by QNimbus** [comment]
I am experiencing the same issue after the 2.4 upgrade. I also get some occasional errors in the OpenHAB log with regard to SSE. (Server side events, which is what the eventsource library is for)

In the meantime I went back to 2.4M6 which was the build that was working flawlessly for me until I figured out what the issue is.

**Comment by QNimbus** [comment]
@bkmar1192 I am using Docker containers myself, so downgrading was as easy as specifying a different image to run as container.

I suggest you look through the official OpenHAB documentation [(Community forum link)](url
https://community.openhab.org/t/openhabian-cannot-revert-to-stable-using-openhabian-menu-item/31715) to find the right way to downgrade your OpenHAB instance for now.
